# Generated by Django 3.1.2 on 2020-10-18 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabourModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('currentLocation', models.CharField(max_length=200)),
                ('gotoLocation', models.CharField(max_length=200)),
                ('aadharNumber', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalPill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PickerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('preferToStayAnonymous', models.BooleanField()),
                ('aadharNumber', models.CharField(max_length=14)),
            ],
        ),
    ]
